version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release

platform:
  - x64

environment:
  VULKAN_SDK: C:/VulkanSDK/1.2.198.1

cache:
  - VulkanSDK.exe

install:
  - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.2.198.1/windows/VulkanSDK-1.2.198.1-Installer.exe?Human=true
  - VulkanSDK.exe in --al --im -c

build_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
  - ninja
