version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release

platform:
  - x64

environment:
  VULKAN_SDK: C:/VulkanSDK/1.1.130.0

cache:
  - VulkanSDK.exe

install:
  - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.130.0/windows/VulkanSDK-1.1.130.0-Installer.exe?Human=true
  - VulkanSDK.exe /S

build_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --config %configuration%
