version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release

platform:
  - x64

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  VULKAN_SDK: C:/VulkanSDK/1.2.198.1

cache:
  - VulkanSDK.exe

install:
  - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.2.198.1/windows/VulkanSDK-1.2.198.1-Installer.exe?Human=true
  - VulkanSDK.exe /S

build_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
  - ninja
